"""Generate the public CLI reference from the Typer command tree."""

from __future__ import annotations

import argparse
import difflib
import html
import sys
from pathlib import Path

import click
import typer.main

from craik.cli import app

ROOT = Path(__file__).resolve().parents[1]
CLI_REFERENCE = ROOT / "docs" / "reference" / "cli.md"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if docs/reference/cli.md is stale.",
    )
    args = parser.parse_args()

    generated = generate_reference()
    if args.check:
        existing = CLI_REFERENCE.read_text(encoding="utf-8")
        if existing != generated:
            diff = difflib.unified_diff(
                existing.splitlines(keepends=True),
                generated.splitlines(keepends=True),
                fromfile=str(CLI_REFERENCE),
                tofile="generated cli reference",
            )
            print("CLI reference is stale. Run scripts/generate_cli_reference.py.", file=sys.stderr)
            print("".join(diff), file=sys.stderr)
            return 1
        print("CLI reference is up to date.")
        return 0

    CLI_REFERENCE.write_text(generated, encoding="utf-8")
    print(f"Wrote {CLI_REFERENCE.relative_to(ROOT)}")
    return 0


def generate_reference() -> str:
    root = typer.main.get_command(app)
    lines = [
        "# CLI Reference",
        "",
        "<!-- Generated by scripts/generate_cli_reference.py. Do not edit by hand. -->",
        "",
        "Craik exposes the `craik` command.",
        "",
        "## Command Groups",
        "",
    ]

    for path, command in _walk_commands(root):
        heading = " ".join(("craik", *path))
        lines.extend([f"## `{heading}`", ""])
        if command.help:
            lines.extend([_mdx_text(command.help.strip()), ""])
        usage = _usage(path, command)
        if usage:
            lines.extend(["```text", usage, "```", ""])
        options = _options(command)
        if options:
            lines.extend(["Options:", ""])
            lines.extend(options)
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _walk_commands(
    command: click.Command,
    path: tuple[str, ...] = (),
) -> list[tuple[tuple[str, ...], click.Command]]:
    entries: list[tuple[tuple[str, ...], click.Command]] = [(path, command)]
    if isinstance(command, click.Group):
        for name in sorted(command.commands):
            entries.extend(_walk_commands(command.commands[name], (*path, name)))
    return entries


def _usage(path: tuple[str, ...], command: click.Command) -> str:
    pieces = ["craik", *path]
    if command.params:
        pieces.append("[OPTIONS]")
    if isinstance(command, click.Group) and command.commands:
        pieces.append("COMMAND [ARGS]...")
    for param in command.params:
        if isinstance(param, click.Argument):
            pieces.append(param.human_readable_name.upper())
    return " ".join(pieces)


def _options(command: click.Command) -> list[str]:
    rendered: list[str] = []
    for param in command.params:
        if not isinstance(param, click.Option):
            continue
        names = ", ".join(param.opts + param.secondary_opts)
        help_text = _mdx_text((param.help or "").strip())
        default = _default_text(param)
        detail = "; ".join(part for part in (help_text, default) if part)
        if detail:
            rendered.append(f"- `{names}`: {detail}")
        else:
            rendered.append(f"- `{names}`")
    return rendered


def _default_text(param: click.Option) -> str:
    if param.default in (None, (), []):
        return ""
    if isinstance(param.default, bool):
        return f"default `{str(param.default).lower()}`"
    return f"default `{_mdx_text(str(param.default))}`"


def _mdx_text(value: str) -> str:
    return html.escape(value, quote=False)


if __name__ == "__main__":
    raise SystemExit(main())
