"""Schema registry for Craik runtime contracts."""

from __future__ import annotations

from pydantic import BaseModel

from craik.contracts.models import (
    AdapterPackage,
    AdjudicationOutcome,
    AgentMessage,
    AgentOnboarding,
    AgentRole,
    Assumption,
    CapabilityGrant,
    CapabilityReceipt,
    CaseFile,
    ChannelAdapterContract,
    ChannelAllowlist,
    ChannelIdentityPairing,
    CompiledPrompt,
    ContextDebtRecord,
    ContextRequest,
    ContradictionReport,
    DebateSummary,
    DebateTurn,
    DistilledInstructionProposal,
    EvidenceCoverageScore,
    EvidenceReference,
    ExitDisciplineCheck,
    GatewayConfig,
    GatewayRuntimeState,
    GatewaySchedule,
    Handoff,
    HandoffQualityScore,
    HumanDelegationPoint,
    InstructionPromotionReview,
    InstructionProvenance,
    InstructionRegistryReceipt,
    InstructionSource,
    InstructionSourceRegistration,
    InstructionSourceRegistry,
    InstructionSourceSnapshot,
    IntentLock,
    KnowledgeFreshnessProbe,
    KnownTrap,
    MemoryBackendCapabilities,
    MemoryDiff,
    MemoryImpactPreview,
    MemoryProposal,
    ModelProvider,
    NegativeKnowledge,
    PluginCapabilityGrant,
    PluginDescriptor,
    PluginProbation,
    PluginReceipt,
    PolicyEnvelope,
    ProjectProfile,
    PromotedInstructionConstraint,
    RecoverySession,
    RedTeamFinding,
    ReferenceIntegration,
    ReviewRequest,
    ReviewResult,
    RunDelta,
    RunnerAdapterRequest,
    RunnerAdapterResult,
    RunnerCapabilityMatrix,
    RunnerMetadata,
    RunnerStepRequest,
    RunnerStepResult,
    RunOutput,
    RuntimeCriticFinding,
    SandboxBackend,
    ScheduledAutomation,
    ScopeChangeRequest,
    ScopeChangeResult,
    ScratchpadRecord,
    SkillInvocationContext,
    SkillPackage,
    SkillRegistry,
    TaskRequest,
    TaskRun,
    ToolResultAttestation,
    UnknownRecord,
    WorkerResult,
    WorkGraphEvent,
    WorkGraphExport,
)

type ContractModel = type[BaseModel]

CONTRACT_REGISTRY: dict[str, ContractModel] = {
    "craik.adjudication_outcome": AdjudicationOutcome,
    "craik.adapter_package": AdapterPackage,
    "craik.agent_message": AgentMessage,
    "craik.agent_onboarding": AgentOnboarding,
    "craik.agent_role": AgentRole,
    "craik.assumption": Assumption,
    "craik.capability_grant": CapabilityGrant,
    "craik.capability_receipt": CapabilityReceipt,
    "craik.case_file": CaseFile,
    "craik.channel_allowlist": ChannelAllowlist,
    "craik.channel_adapter_contract": ChannelAdapterContract,
    "craik.channel_identity_pairing": ChannelIdentityPairing,
    "craik.compiled_prompt": CompiledPrompt,
    "craik.contradiction_report": ContradictionReport,
    "craik.context_debt_record": ContextDebtRecord,
    "craik.context_request": ContextRequest,
    "craik.debate_summary": DebateSummary,
    "craik.debate_turn": DebateTurn,
    "craik.distilled_instruction_proposal": DistilledInstructionProposal,
    "craik.evidence_reference": EvidenceReference,
    "craik.exit_discipline_check": ExitDisciplineCheck,
    "craik.evidence_coverage_score": EvidenceCoverageScore,
    "craik.gateway_config": GatewayConfig,
    "craik.gateway_runtime_state": GatewayRuntimeState,
    "craik.gateway_schedule": GatewaySchedule,
    "craik.handoff": Handoff,
    "craik.handoff_quality_score": HandoffQualityScore,
    "craik.human_delegation_point": HumanDelegationPoint,
    "craik.instruction_source": InstructionSource,
    "craik.instruction_source_registration": InstructionSourceRegistration,
    "craik.instruction_registry_receipt": InstructionRegistryReceipt,
    "craik.instruction_provenance": InstructionProvenance,
    "craik.instruction_source_registry": InstructionSourceRegistry,
    "craik.instruction_source_snapshot": InstructionSourceSnapshot,
    "craik.instruction_promotion_review": InstructionPromotionReview,
    "craik.intent_lock": IntentLock,
    "craik.knowledge_freshness_probe": KnowledgeFreshnessProbe,
    "craik.known_trap": KnownTrap,
    "craik.memory_backend_capabilities": MemoryBackendCapabilities,
    "craik.memory_diff": MemoryDiff,
    "craik.memory_impact_preview": MemoryImpactPreview,
    "craik.memory_proposal": MemoryProposal,
    "craik.model_provider": ModelProvider,
    "craik.negative_knowledge": NegativeKnowledge,
    "craik.policy_envelope": PolicyEnvelope,
    "craik.plugin_capability_grant": PluginCapabilityGrant,
    "craik.plugin_descriptor": PluginDescriptor,
    "craik.plugin_probation": PluginProbation,
    "craik.plugin_receipt": PluginReceipt,
    "craik.project_profile": ProjectProfile,
    "craik.promoted_instruction_constraint": PromotedInstructionConstraint,
    "craik.reference_integration": ReferenceIntegration,
    "craik.red_team_finding": RedTeamFinding,
    "craik.recovery_session": RecoverySession,
    "craik.review_request": ReviewRequest,
    "craik.review_result": ReviewResult,
    "craik.run_delta": RunDelta,
    "craik.run_output": RunOutput,
    "craik.runtime_critic_finding": RuntimeCriticFinding,
    "craik.scheduled_automation": ScheduledAutomation,
    "craik.sandbox_backend": SandboxBackend,
    "craik.scratchpad_record": ScratchpadRecord,
    "craik.scope_change_request": ScopeChangeRequest,
    "craik.scope_change_result": ScopeChangeResult,
    "craik.skill_invocation_context": SkillInvocationContext,
    "craik.skill_package": SkillPackage,
    "craik.skill_registry": SkillRegistry,
    "craik.runner_adapter_request": RunnerAdapterRequest,
    "craik.runner_adapter_result": RunnerAdapterResult,
    "craik.runner_capability_matrix": RunnerCapabilityMatrix,
    "craik.runner_metadata": RunnerMetadata,
    "craik.runner_step_request": RunnerStepRequest,
    "craik.runner_step_result": RunnerStepResult,
    "craik.task_run": TaskRun,
    "craik.task_request": TaskRequest,
    "craik.tool_result_attestation": ToolResultAttestation,
    "craik.unknown_record": UnknownRecord,
    "craik.work_graph_export": WorkGraphExport,
    "craik.work_graph_event": WorkGraphEvent,
    "craik.worker_result": WorkerResult,
}


def schema_names() -> list[str]:
    """Return known schema names in stable order."""
    return sorted(CONTRACT_REGISTRY)


def schema_model(name: str) -> ContractModel:
    """Return the Pydantic model registered for a schema name."""
    return CONTRACT_REGISTRY[name]
